spring:
  security:
    user:
      name: gehan
      password: 1234

  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update